# @package _global_

defaults:
  - _gat
  - override /task: poisson
  - _self_

exp_name: gat_poisson
_version: 1

trainer:
  max_epochs: 201
idx: gat100

hydra:
  sweeper:
    ablative_params:
      - task.refinement_heuristic.refinement_steps: 25
        idx: gat100e  # "e" for "easy"
      - task.refinement_heuristic.refinement_steps: 50
        idx: gat100m  # "m" for "medium"

      # One-step
      - algorithm.inference_steps: 1
        task.max_initial_element_volume: 0.00003
        idx: stp100
      - algorithm.inference_steps: 1
        task.max_initial_element_volume: 0.0005
        task.refinement_heuristic.refinement_steps: 25
        idx: stp100e
      - algorithm.inference_steps: 1
        task.max_initial_element_volume: 0.0001
        task.refinement_heuristic.refinement_steps: 50
        idx: stp100m
