# @package _global_

defaults:
  - _gat
  - override /task: airfoil
  - _self_

exp_name: gat_airfoil
_version: 1
trainer:
  max_epochs: 101
idx: gat100

hydra:
  sweeper:
    ablative_params:
      - algorithm.inference_steps: 1
        task.max_initial_element_volume: 0.0003
        idx: stp100
